#pragma once

/*
	yuki 结构的名称
*/
#define yuki_document_name								L"document"
#define yuki_section_name								L"section"
#define yuki_body_name									L"body"
#define yuki_rst_header_name							L"rst_header"
#define yuki_md_header_name								L"md_header"
#define yuki_inline_block_name							L"inline_block"
#define yuki_inline_markup_name							L"inline_markup"
#define yuki_inline_bold_italic_name					L"inline_bold_italic"
#define yuki_inline_code_name							L"inline_code"
#define yuki_inline_deleted_name						L"inline_deleted"
#define yuki_inline_emphasis_name						L"inline_emphasis"
#define yuki_inline_format_name							L"inline_format"
#define yuki_inline_key_name							L"inline_key"
#define yuki_inline_marked_name							L"inline_marked"
#define yuki_inline_strong_name							L"inline_strong"
#define yuki_inline_sub_name							L"inline_sub"
#define yuki_inline_sup_name							L"inline_sup"
#define yuki_inline_underline_name						L"inline_underline"
#define yuki_link_uri_name								L"link_uri"
#define yuki_plain_text_name							L"plain_text"
#define yuki_reserved_text_name							L"reserved_text"
#define yuki_simple_reference_name_name					L"simple_reference_name"
#define yuki_doctest_block_name							L"doctest"
#define yuki_literal_block_name							L"literal_block"
#define yuki_rst_literal_block_name						L"rst_literal_block"
#define yuki_md_literal_block_name						L"md_literal_block"
#define yuki_quote_block_name							L"quote_block"
#define yuki_quote_block_attribute_name					L"quote_block_attribute"
#define yuki_rst_quote_block_name						L"rst_quote_block"
#define yuki_md_quote_block_name						L"md_quote_block"
#define yuki_paragraph_block_name						L"paragraph"
#define yuki_comment_block_name							L"comment"
#define yuki_directives_block_name						L"directives"
#define yuki_explicit_markup_block_name					L"explicit_markup"
#define yuki_footnote_citation_definition_block_name	L"footnote_citation_definition"
#define yuki_hyperlink_target_block_name				L"hyperlink_target"
#define yuki_substitution_definition_block_name			L"substitution_definition"
